engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- features/
- Sample-Images/**/*
- artwork/**/*
- data/**/*
- design/**/*
- docs/**/*
- end-to-end-tests/**/*
- munin-plugins/**/*
- open-source-docker/**/*
- travis-ci/**/*
- ubuntu/**/*
- web-server/css/**/*
- web-server/fonts/**/*
- web-server/js/**/*
- "**.md"
- "**.yml"
- "**.csv"
- "**.jpg"
- "**.hdf5"
- "**.stl"
- "**.js"