exclude_paths:
- Sample-Images/**/*
- artwork/**/*
- data/**/*
- design/**/*
- docs/**/*
- end-to-end-tests/**/*
- munin-plugins/**/*
- open-source-docker/**/*
- travis-ci/**/*
- ubuntu/**/*
- "**.md"
- "**.yml"
- "**.csv"